ORDINAL = ['Overall Cond', 'MS SubClass', 'Overall Qual']

CAT_GROUPS = {
    "Lot & Location": {
        'MS Zoning': [
            'A Agriculture',
            'C Commercial',
            'FV Floating Village Residential',
            'I Industrial',
            'RH Residential High Density',
            'RL Residential Low Density',
            'RP Residential Low Density Park',
            'RM Residential Medium Density',
        ],
        'Lot Shape': [
            'Reg Regular',
            'IR1 Slightly irregular',
            'IR2 Moderately Irregular',
            'IR3 Irregular',
        ],
        'Land Contour': [
            'Lvl Near Flat/Level',
            'Bnk Banked - Quick and significant rise from street grade to building',
            'HLS Hillside - Significant slope from side to side',
            'Low Depression',
        ],
        'Lot Config': [
            'Inside Inside lot',
            'Corner Corner lot',
            'CulDSac Cul-de-sac',
            'FR2 Frontage on 2 sides of property',
            'FR3 Frontage on 3 sides of property',
        ],
        'Condition 1': [
            'Artery Adjacent to arterial street',
            'Feedr Adjacent to feeder street',
            'Norm Normal',
            "RRNn Within 200' of North-South Railroad",
            'RRAn Adjacent to North-South Railroad',
            'PosN Near positive off-site feature--park, greenbelt, etc.',
            'PosA Adjacent to postive off-site feature',
            "RRNe Within 200' of East-West Railroad",
            'RRAe Adjacent to East-West Railroad',
        ],
    },
    "Building": {
        'MS SubClass': [
            '20 1-STORY 1946 & NEWER ALL STYLES',
            '30 1-STORY 1945 & OLDER',
            '40 1-STORY W/FINISHED ATTIC ALL AGES',
            '45 1-1/2 STORY - UNFINISHED ALL AGES',
            '50 1-1/2 STORY FINISHED ALL AGES',
            '60 2-STORY 1946 & NEWER',
            '70 2-STORY 1945 & OLDER',
            '75 2-1/2 STORY ALL AGES',
            '80 SPLIT OR MULTI-LEVEL',
            '85 SPLIT FOYER',
            '90 DUPLEX - ALL STYLES AND AGES',
            '120 1-STORY PUD (Planned Unit Development) - 1946 & NEWER',
            '150 1-1/2 STORY PUD - ALL AGES',
            '160 2-STORY PUD - 1946 & NEWER',
            '180 PUD - MULTILEVEL - INCL SPLIT LEV/FOYER',
            '190 2 FAMILY CONVERSION - ALL STYLES AND AGES',
        ],
        'Bldg Type': [
            '1Fam Single-family Detached',
            '2FmCon Two-family Conversion; originally built as one-family dwelling',
            'Duplx Duplex',
            'TwnhsE Townhouse End Unit',
            'TwnhsI Townhouse Inside Unit',
        ],
        'House Style': [
            '1Story One story',
            '1.5Fin One and one-half story: 2nd level finished',
            '1.5Unf One and one-half story: 2nd level unfinished',
            '2Story Two story',
            '2.5Fin Two and one-half story: 2nd level finished',
            '2.5Unf Two and one-half story: 2nd level unfinished',
            'SFoyer Split Foyer',
            'SLvl Split Level',
        ],
        'Overall Qual': [
            '10 Very Excellent',
            '9 Excellent',
            '8 Very Good',
            '7 Good',
            '6 Above Average',
            '5 Average',
            '4 Below Average',
            '3 Fair',
            '2 Poor',
            '1 Very Poor',
        ],
        'Overall Cond': [
            '10 Very Excellent',
            '9 Excellent',
            '8 Very Good',
            '7 Good',
            '6 Above Average',
            '5 Average',
            '4 Below Average',
            '3 Fair',
            '2 Poor',
            '1 Very Poor',
        ],
        'Roof Style': [
            'Flat Flat',
            'Gable Gable',
            'Gambrel Gabrel (Barn)',
            'Hip Hip',
            'Mansard Mansard',
            'Shed Shed',
        ],
        'Exterior 1st': [
            'AsbShng Asbestos Shingles',
            'AsphShn Asphalt Shingles',
            'BrkComm Brick Common',
            'BrkFace Brick Face',
            'CBlock Cinder Block',
            'CemntBd Cement Board',
            'HdBoard Hard Board',
            'ImStucc Imitation Stucco',
            'MetalSd Metal Siding',
            'Other Other',
            'Plywood Plywood',
            'PreCast PreCast',
            'Stone Stone',
            'Stucco Stucco',
            'VinylSd Vinyl Siding',
            'Wd Sdng Wood Siding',
            'WdShing Wood Shingles',
        ],
        'Exterior 2nd': [
            'AsbShng Asbestos Shingles',
            'AsphShn Asphalt Shingles',
            'BrkComm Brick Common',
            'BrkFace Brick Face',
            'CBlock Cinder Block',
            'CemntBd Cement Board',
            'HdBoard Hard Board',
            'ImStucc Imitation Stucco',
            'MetalSd Metal Siding',
            'Other Other',
            'Plywood Plywood',
            'PreCast PreCast',
            'Stone Stone',
            'Stucco Stucco',
            'VinylSd Vinyl Siding',
            'Wd Sdng Wood Siding',
            'WdShing Wood Shingles',
        ],
        'Exter Qual': [
            'Ex Excellent',
            'Gd Good',
            'TA Average/Typical',
            'Fa Fair',
            'Po Poor',
        ],
        'Exter Cond': [
            'Ex Excellent',
            'Gd Good',
            'TA Average/Typical',
            'Fa Fair',
            'Po Poor',
        ],
        'Foundation': [
            'BrkTil Brick & Tile',
            'CBlock Cinder Block',
            'PConc Poured Contrete',
            'Slab Slab',
            'Stone Stone',
            'Wood Wood',
        ],
    },
    "Basement": {
        'Bsmt Cond': [
            'Ex Excellent',
            'Gd Good',
            'TA Typical - slight dampness allowed',
            'Fa Fair - dampness or some cracking or settling',
            'Po Poor - Severe cracking, settling, or wetness',
            'NA No Basement',
        ],
    },
    "Utilities": {
        'Heating QC': [
            'Ex Excellent',
            'Gd Good',
            'TA Average/Typical',
            'Fa Fair',
            'Po Poor',
        ],
        'Central Air': [
            'N No',
            'Y Yes',
        ],
        'Kitchen Qual': [
            'Ex Excellent',
            'Gd Good',
            'TA Typical/Average',
            'Fa Fair',
            'Po Poor',
        ],
    },
    "Garage": {
        'Garage Type': [
            '2Types More than one type of garage',
            'Attchd Attached to home',
            'Basment Basement Garage',
            'BuiltIn Built-In (Garage part of house - typically has room above garage)',
            'CarPort Car Port',
            'Detchd Detached from home',
            'NA No Garage',
        ],
        'Garage Finish': [
            'Fin Finished',
            'RFn Rough Finished',
            'Unf Unfinished',
            'NA No Garage',
        ],
        'Garage Qual': [
            'Ex Excellent',
            'Gd Good',
            'TA Typical/Average',
            'Fa Fair',
            'Po Poor',
            'NA No Garage',
        ],
    },
}

CAT = {field: options
       for group in CAT_GROUPS.values()
       for field, options in group.items()}


NUM_GROUPS = {
    "Lot": {
        'Lot Frontage': [21,   131,   1, "%i"],
        'Lot Area':     [1300, 23595, 1, "%i"],
    },
    "House": {
        'Gr Liv Area':    [334,  3493, 1, "%i"],
        '2nd Flr SF':     [0,    1818, 1, "%i"],
        'Year Built':     [1880, 2010, 1, "%i"],
        'Year Remod/Add': [1950, 2010, 1, "%i"],
    },
    "Basement": {
        'Total Bsmt SF':  [0, 2524, 1, "%i"],
        'Bsmt Full Bath': [0, 3,    1, "%i"],
    },
    "Rooms": {
        'Full Bath':     [0, 3,  1, "%i"],
        'Half Bath':     [0, 2,  1, "%i"],
        'Bedroom AbvGr': [0, 6,  1, "%i"],
        'TotRms AbvGrd': [2, 12, 1, "%i"],
        'Fireplaces':    [0, 3,  1, "%i"],
    },
    "Garage": {
        'Garage Area': [0, 1248, 1, "%i"],
    },
    "Outside": {
        'Wood Deck SF':  [0, 668, 1, "%i"],
        'Open Porch SF': [0, 276, 1, "%i"],
    },
}

NUM = {field: params
       for group in NUM_GROUPS.values()
       for field, params in group.items()}

ONE_STORY_STYLES = {'1Story', '1.5Fin', '1.5Unf', 'SFoyer', 'SLvl'}
